os:
  - osx
  - linux
osx_image: xcode9
language: generic
sudo: required
dist: trusty
env:
  global:
    - SWIFT_VERSION=4.0
  matrix:
    - SWIFTPM_BUILD=true
    - SWIFTPM_TEST=true
    - XCODE_TEST_SDK=macosx
    - XCODE_BUILD_SDK=iphonesimulator
    - XCODE_BUILD_SDK=appletvsimulator
    - XCODE_BUILD_SDK=watchsimulator

matrix:
  exclude:
    # No need to build and test on macOS
    - os: osx
      env: SWIFTPM_BUILD=true
    # LinuxMain.swift is out of sync
    - os: linux
      env: SWIFTPM_TEST=true
    - os: linux
      env: XCODE_TEST_SDK=macosx
    - os: linux
      env: XCODE_BUILD_SDK=iphonesimulator
    - os: linux
      env: XCODE_BUILD_SDK=appletvsimulator
    - os: linux
      env: XCODE_BUILD_SDK=watchsimulator

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
- swift test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project JWT.xcodeproj -scheme JWT-OSX test -sdk macosx; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project JWT.xcodeproj -scheme JWT-iOS build -sdk iphonesimulator; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project JWT.xcodeproj -scheme JWT-tvOS build -sdk appletvsimulator; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project JWT.xcodeproj -scheme JWT-watchOS build -sdk watchsimulator; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pod lib lint; fi
